/**
 * 鲁班 AI 新闻 - 每日自动获取
 * 从 Hacker News 和 Reddit 采集 AI/ML 相关新闻
 */

const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

const config = require('./config.json');

// AI/ML 相关关键词
const AI_KEYWORDS = [
  'AI', 'artificial intelligence', 'machine learning', 'ML',
  'neural', 'deep learning', 'LLM', 'GPT', 'transformer',
  'NLP', 'computer vision', 'reinforcement learning'
];

// 检查标题是否包含 AI 关键词
function isAIRelated(title) {
  const lowerTitle = title.toLowerCase();
  return AI_KEYWORDS.some(keyword => 
    lowerTitle.includes(keyword.toLowerCase())
  );
}

// 获取 Hacker News Top Stories
async function fetchHackerNews() {
  console.log('📰 获取 Hacker News...');
  
  try {
    // 获取 Top Stories IDs
    const topStoriesRes = await fetch(config.hackerNews.url);
    const storyIds = await topStoriesRes.json();
    
    const news = [];
    
    // 获取前 N 个故事的详情
    for (let i = 0; i < Math.min(storyIds.length, config.hackerNews.limit); i++) {
      const id = storyIds[i];
      const itemRes = await fetch(`${config.hackerNews.itemUrl}${id}.json`);
      const item = await itemRes.json();
      
      if (item && item.title && isAIRelated(item.title)) {
        news.push({
          title: item.title,
          url: item.url || `https://news.ycombinator.com/item?id=${id}`,
          score: item.score,
          source: 'Hacker News'
        });
      }
    }
    
    console.log(`✅ Hacker News: 找到 ${news.length} 条 AI 相关新闻`);
    return news;
    
  } catch (error) {
    console.error('❌ Hacker News 获取失败:', error.message);
    return [];
  }
}

// 获取 Reddit r/MachineLearning 热门帖子
async function fetchReddit() {
  console.log('🤖 获取 Reddit r/MachineLearning...');
  
  try {
    const res = await fetch(config.reddit.url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; LubanAI/1.0)'
      }
    });
    
    const data = await res.json();
    const news = [];
    
    const posts = data.data?.children || [];
    
    for (let i = 0; i < Math.min(posts.length, config.reddit.limit); i++) {
      const post = posts[i].data;
      
      if (post.title && !post.over_18) { // 排除 NSFW
        news.push({
          title: post.title,
          url: post.url || `https://reddit.com${post.permalink}`,
          score: post.score,
          source: 'Reddit'
        });
      }
    }
    
    console.log(`✅ Reddit: 找到 ${news.length} 条相关新闻`);
    return news;
    
  } catch (error) {
    console.error('❌ Reddit 获取失败:', error.message);
    return [];
  }
}

// 生成 Markdown 报告
function generateMarkdown(hackerNews, reddit, date) {
  const today = date || new Date();
  const dateStr = today.toISOString().split('T')[0];
  
  let md = `# AI 新闻日报 - ${dateStr}\n\n`;
  md += `> 自动采集自 Hacker News 和 Reddit r/MachineLearning\n\n`;
  md += `---\n\n`;
  
  // Hacker News 部分
  md += `## 📰 Hacker News Top Stories\n\n`;
  if (hackerNews.length > 0) {
    hackerNews.forEach((item, i) => {
      md += `${i + 1}. [${item.title}](${item.url}) ⭐${item.score}\n`;
    });
  } else {
    md += `*今日无 AI 相关新闻*\n`;
  }
  md += `\n`;
  
  // Reddit 部分
  md += `## 🤖 Reddit r/MachineLearning\n\n`;
  if (reddit.length > 0) {
    reddit.forEach((item, i) => {
      md += `${i + 1}. [${item.title}](${item.url}) ⭐${item.score}\n`;
    });
  } else {
    md += `*今日无相关新闻*\n`;
  }
  md += `\n`;
  
  // 摘要
  md += `---\n\n`;
  md += `## 📊 摘要\n\n`;
  md += `今日共收集 **${hackerNews.length + reddit.length}** 条 AI 相关新闻：\n`;
  md += `- Hacker News: ${hackerNews.length} 条\n`;
  md += `- Reddit: ${reddit.length} 条\n\n`;
  md += `---\n\n`;
  md += `*Generated by 鲁班 AI 新闻*\n`;
  
  return md;
}

// 保存文件
function saveFile(content, date) {
  const today = date || new Date();
  const dateStr = today.toISOString().split('T')[0];
  const outputDir = path.join(__dirname, config.output.dir);
  
  // 创建输出目录
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  const filePath = path.join(outputDir, `${dateStr}.md`);
  fs.writeFileSync(filePath, content, 'utf-8');
  
  console.log(`✅ 新闻文件已保存：${filePath}`);
  return filePath;
}

// 主函数
async function main() {
  console.log('🚀 鲁班 AI 新闻 - 开始采集\n');
  
  // 获取新闻
  const [hackerNews, reddit] = await Promise.all([
    fetchHackerNews(),
    fetchReddit()
  ]);
  
  // 生成报告
  const markdown = generateMarkdown(hackerNews, reddit);
  
  // 保存文件
  const filePath = saveFile(markdown);
  
  console.log('\n✅ 采集完成！');
  console.log(`📁 输出文件：${filePath}`);
  
  // 返回文件路径供 GitHub 提交使用
  return { filePath, date: new Date().toISOString().split('T')[0] };
}

// 运行
if (require.main === module) {
  main().catch(console.error);
}

module.exports = { main, fetchHackerNews, fetchReddit, generateMarkdown };
